modLoader="javafml"
loaderVersion="[1,)"
license="GPL-v3"

[properties]
"connector:placeholder"=true

[[mods]]
modId="omnilib"
version="0.1.4"
displayName="Omnilib"
authors="Dooji"
description='''Omnilib is a framework for exploring new possibilities in Minecraft modding.'''
logoFile="assets/omnilib/icon.png"

[[dependencies.omnilib]]
modId="neoforge"
mandatory=true
versionRange="[1,)"
ordering="NONE"
side="BOTH"

[[dependencies.omnilib]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.omnilib]]
modId="connector"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"